Add cloud-agnostic CloudClient interface
openshift/cloud-ingress-operator pull request #120
Opened 2020-10-23 14:52 UTC by mbarnes

This is the completion of @lisa's https://github.com/lisa/cloud-ingress-operator/tree/osd-3566 branch.

This was a collective Team Rocket effort, so apologies for the messy commit history.

All controllers have been updated to use the new `CloudClient` interface.

The utility functions proved hardest to wrangle.  I've introduced a new `pkg/utils` subpackage which conceptually sits "below" the  `pkg/controller` and `pkg/cloudclient` layers so as to avoid import loops.  This is where `GetInfrastructureObject` and most of the utilities that rely on it ended up.

2020-10-26 12:32 UTC, lisa commented
/hold

(for review and eventual squashing)

2020-10-26 12:33 UTC, lisa commented
/cc @lisa

2020-10-26 23:43 UTC, lisa requested changes
What is the status of testing in-cluster here?

Love to see this getting to PR state.

Can we consolidate commits as per Slack convo?

2020-10-27 18:20 UTC, mbarnes commented on pkg/cloudclient/aws/private.go
> +// getAWSDecodedProviderSpec casts the spec.providerSpec of a kubernetes machine
:heavy_check_mark:

2020-10-27 18:24 UTC, mbarnes commented on pkg/cloudclient/aws/private.go
> +}
I think it got dragged in with `GetMasterNodeSubnets`, but I'll split it back out.

2020-10-27 19:22 UTC, mbarnes commented on pkg/cloudclient/aws/private.go
> +}
:heavy_check_mark:

2020-10-27 19:24 UTC, mbarnes commented on pkg/cloudclient/aws/private.go
> +func AddAWSLBToMasterMachines(kclient client.Client, elbName string, masterNodes *machineapi.MachineList) error {
:heavy_check_mark:

2020-10-27 19:27 UTC, mbarnes commented on pkg/cloudclient/aws/private_test.go
> +	// TODO: Fill this in
Looks like that comment's been there awhile.  I see a test case so I assume it's completed.

2020-10-27 19:28 UTC, mbarnes commented on pkg/cloudclient/aws/private_test.go
> +	// TODO: Fill this in
:heavy_check_mark:

2020-10-27 19:43 UTC, mbarnes commented
I've cleaned up the commit history so it shows a more concise and straight-forward progression, while retaining proper authorship.  Also addressed all review comments so far.  Force-pushing the cleaner commit list.

> What is the status of testing in-cluster here?
Everything seemed to be working before I started messing with commits.  I'll re-verify.

2020-10-27 19:44 UTC, mbarnes commented on pkg/controller/publishingstrategy/publishingstrategy_controller.go
> +		log.Info("Update api.<clusterName> alias to internal NLB successful")
:heavy_check_mark:

2020-10-27 19:44 UTC, mbarnes commented on pkg/controller/publishingstrategy/publishingstrategy_controller.go
> +		log.Info("Update api.<clusterName> alias to internal NLB successful")
:heavy_check_mark:

2020-10-28 14:54 UTC, lisa commented
It is with great pleasure that I get to be the one to do this:

/lgtm

:shipit:   🎉 👍 

Great work to everyone involved with this port.


@mbarnes Please `/unhold` when ready to merge.

2020-10-28 15:26 UTC, lisa approved these changes

2020-10-28 15:28 UTC, merged