Ensure API server ingress visibility reconciled before disowning application ingress
openshift/cloud-ingress-operator pull request #313
Opened 2023-11-02 23:17 UTC by hectorakemp

Based on a bug found by OCM (https://redhat-internal.slack.com/archives/CCX9DB894/p1698859611466809), we realised that we were **not** reconciling the `defaultAPIServerIngress` before returning the `applicationIngress` to the `cluster-ingress-operator`. 

This pull request fixes that by adding a call to `ensureAliasScope` before releasing ownership of the ingress. Unit tests to verify the call to `ensureAliasScope` are also added.

2023-11-03 19:50 UTC, sam-nguyen7 requested changes

2023-11-03 19:50 UTC, sam-nguyen7 commented on controllers/publishingstrategy/publishingstrategy_controller.go
> +		result, err = r.ensureAliasScope(reqLogger, instance, clusterBaseDomain)
We should move `ensureAliasScope` out as we want the scope of default API server to match scope of publishing strategy CR for both native ingress controller and managed ingress

2023-11-06 09:49 UTC, gdbranco approved these changes

2023-11-06 13:39 UTC, sam-nguyen7 approved these changes
/lgtm
/approve

2023-11-06 13:42 UTC, merged